### ISSUE TITLE
can you make openssl-1.0.1k support?

### ISSUE THREAD

**Issue by toontong** [ptudor/centos6-openssl#11]
can you make openssl-1.0.1k support?

**Comment by neverping** [comment]
Doing.

**Comment by neverping** [comment]
Done. 
I did on CentOS 5.8 64 bits, but I still need to test it against CentOS 6. You can check it out at my clone repo at https://github.com/neverping/centos6-openssl 

I will ask for a merge when I finish testing it.

**Comment by toontong** [comment]
good job

**Comment by toontong** [comment]
error: Failed build dependencies:
	buildsys-macros is needed by openssl-1:1.0.1k-1.el5.x86_64

**Comment by neverping** [comment]
Hello @toontong 
I've corrected the BuildRequires. Can you check if it will work for you, please?
Thanks!
