### ISSUE TITLE
this openssl is crippled to only support 3 curves

### ISSUE THREAD

**Issue by tittof** [ptudor/centos6-openssl#8]
The ptudor package used not to disable all the curves that are normally supported by openssl but intentionally crippled by RedHat.

**Comment by neverping** [comment]
Hello @tittof 

I think OpenSSL compiles by default with ec2m support. They just make it possible to disable it in case you need it.

http://wiki.openssl.org/index.php/Compilation_and_Installation#Configure_Options

no-ec2m - "Used when configuring FIPS Capable Library with a FIPS Object Module that only includes prime curves. That is, use this switch if you use openssl-fips-ecp-2.0.5. "

So if you want with ec2m, just remove the flag.
PS: I just got this error:

../libcrypto.so: undefined reference to `fips_ec_gf2m_simple_method'

**Comment by tittof** [comment]
yeah do not enable it in the configure. As I said it's not working with ec2m :)

But pull https://github.com/tittof/centos6-openssl i updated to latest

**Comment by neverping** [comment]
Hello @tittof.
User @richbria made two pull requests, which bumped openssl to 1.0.1k version. I already merged his contribution with my own repo.

Made a small test in my virtualbox and it seens ok
(...)
data content test streaming PEM format: OK
encrypted content test streaming PEM format, 128 bit RC2 key: OK
encrypted content test streaming PEM format, 40 bit RC2 key: OK
encrypted content test streaming PEM format, triple DES key: OK
encrypted content test streaming PEM format, 128 bit AES key: OK
compressed content test streaming PEM format: OK
ALL TESTS SUCCESSFUL.
../util/shlib_wrap.sh ./heartbeat_test
Test constant time utilites
../util/shlib_wrap.sh ./constant_time_test
Testing constant time operations...
ok (ran 1908 tests)
make: Leaving directory `/root/rpmbuild/BUILD/openssl-1.0.1k/test'
(...)
Wrote: /root/rpmbuild/SRPMS/openssl-1.0.1k-1.el6.src.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/openssl-1.0.1k-1.el6.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/openssl-libs-1.0.1k-1.el6.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/openssl-devel-1.0.1k-1.el6.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/openssl-static-1.0.1k-1.el6.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/openssl-perl-1.0.1k-1.el6.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.8A3wUI
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd openssl-1.0.1k
+ '[' /root/rpmbuild/BUILDROOT/openssl-1.0.1k-1.el6.x86_64 '!=' / ']'
+ rm -rf /root/rpmbuild/BUILDROOT/openssl-1.0.1k-1.el6.x86_64
+ exit 0
[root@localhost SPECS]# 
[root@localhost SPECS]# cd /root/rpmbuild/RPMS/x86_64/
[root@localhost x86_64]# openssl version
OpenSSL 1.0.1j-fips 15 Oct 2014
[root@localhost x86_64]# rpm -Uvh openssl-*
Preparing...                ########################################### [100%]
   1:openssl-libs           ########################################### [ 20%]
   2:openssl                ########################################### [ 40%]
   3:openssl-devel          ########################################### [ 60%]
   4:openssl-static         ########################################### [ 80%]
   5:openssl-perl           ########################################### [100%]
[root@localhost x86_64]# openssl version
OpenSSL 1.0.1k-fips 8 Jan 2015
[root@localhost x86_64]# 

I think it's good for a pull request.

**Comment by richbria** [comment]
My pull request is already merge in but it was only changes to the readme.

I noticed we are missing some other curves.  My openssl-libs-1.0.1j (i just built from this repo) has the following curves missing:
sect113r1 : SECG curve over a 113 bit binary field
  sect113r2 : SECG curve over a 113 bit binary field
  sect131r1 : SECG/WTLS curve over a 131 bit binary field
  sect131r2 : SECG curve over a 131 bit binary field
  sect163k1 : NIST/SECG/WTLS curve over a 163 bit binary field
  sect163r1 : SECG curve over a 163 bit binary field
  sect163r2 : NIST/SECG curve over a 163 bit binary field
  sect193r1 : SECG curve over a 193 bit binary field
  sect193r2 : SECG curve over a 193 bit binary field
  sect233k1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect233r1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect239k1 : SECG curve over a 239 bit binary field
  sect283k1 : NIST/SECG curve over a 283 bit binary field
  sect283r1 : NIST/SECG curve over a 283 bit binary field
  sect409k1 : NIST/SECG curve over a 409 bit binary field
  sect409r1 : NIST/SECG curve over a 409 bit binary field
  sect571k1 : NIST/SECG curve over a 571 bit binary field
  sect571r1 : NIST/SECG curve over a 571 bit binary field
  c2pnb163v1: X9.62 curve over a 163 bit binary field
  c2pnb163v2: X9.62 curve over a 163 bit binary field
  c2pnb163v3: X9.62 curve over a 163 bit binary field
  c2pnb176v1: X9.62 curve over a 176 bit binary field
  c2tnb191v1: X9.62 curve over a 191 bit binary field
  c2tnb191v2: X9.62 curve over a 191 bit binary field
  c2tnb191v3: X9.62 curve over a 191 bit binary field
  c2pnb208w1: X9.62 curve over a 208 bit binary field
  c2tnb239v1: X9.62 curve over a 239 bit binary field
  c2tnb239v2: X9.62 curve over a 239 bit binary field
  c2tnb239v3: X9.62 curve over a 239 bit binary field
  c2pnb272w1: X9.62 curve over a 272 bit binary field
  c2pnb304w1: X9.62 curve over a 304 bit binary field
  c2tnb359v1: X9.62 curve over a 359 bit binary field
  c2pnb368w1: X9.62 curve over a 368 bit binary field
  c2tnb431r1: X9.62 curve over a 431 bit binary field
  wap-wsg-idm-ecid-wtls1: WTLS curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls3: NIST/SECG/WTLS curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls4: SECG curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls5: X9.62 curve over a 163 bit binary field

**Comment by tittof** [comment]
That's what I'm saying.

do not enable ec2m. It is NOT working. That is why some curves are missing. You would have to get the fips specific patches for it and I really recommend not to try to do that unless you are loving severe headaches.

Since it's only documentation.

Fetch what I provide at https://github.com/tittof/centos6-openssl

Merge with your documentation. Essentially the Changes weren't very big. Just Diff

**Comment by richbria** [comment]
@ptudor The variant that you have on your blog here: https://www.ptudor.net/linux/openssl/resources/openssl-1.0.1h-1.el6.src.rpm

Do you know what was different between that build and this repository?

**Comment by neverping** [comment]
@richbria and @tittof :
I will download the @ptudor 's tutorial and check what we have missed.

**Comment by neverping** [comment]
Ok, downloaded the src.rpm from ptudor's site and.... it doesnt' work.

[root@localhost SPECS]# rpm -qa |grep openssl
openssl-1.0.1e-15.el6.x86_64
[root@localhost SPECS]# cd ../
[root@localhost rpmbuild]# cd ^C
[root@localhost rpmbuild]# rpm -Uvh RPMS/x86_64/openssl-1.0.1h-1.el6.x86_64.rpm 
error: Failed dependencies:
	libcrypto.so.10()(64bit) is needed by openssl-1:1.0.1h-1.el6.x86_64
	libcrypto.so.10(OPENSSL_1.0.1)(64bit) is needed by openssl-1:1.0.1h-1.el6.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by openssl-1:1.0.1h-1.el6.x86_64
	libssl.so.10()(64bit) is needed by openssl-1:1.0.1h-1.el6.x86_64
	libssl.so.10(libssl.so.10)(64bit) is needed by openssl-1:1.0.1h-1.el6.x86_64
	openssl-libs(x86-64) = 1:1.0.1h-1.el6 is needed by openssl-1:1.0.1h-1.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) libssh2-1.4.2-1.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) bind-libs-32:9.8.2-0.17.rc1.el6_4.6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) mysql-libs-5.1.71-1.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) fipscheck-1.2.0-7.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) python-libs-2.6.6-51.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) openssh-5.3p1-94.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) ntpdate-4.2.6p5-1.el6.centos.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) cyrus-sasl-2.1.23-13.el6_3.1.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) postfix-2:2.6.6-2.2.el6_1.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) ntp-4.2.6p5-1.el6.centos.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) openssh-server-5.3p1-94.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) openssh-clients-5.3p1-94.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) bind-utils-32:9.8.2-0.17.rc1.el6_4.6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) tcpdump-14:4.0.0-3.20090921gitdf3cb4.2.el6.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) wget-1.12-1.11.el6_5.x86_64
	libcrypto.so.10()(64bit) is needed by (installed) git-1.7.1-3.el6_4.1.x86_64
	libcrypto.so.10(OPENSSL_1.0.1)(64bit) is needed by (installed) openssh-5.3p1-94.el6.x86_64
	libcrypto.so.10(OPENSSL_1.0.1)(64bit) is needed by (installed) ntpdate-4.2.6p5-1.el6.centos.x86_64
	libcrypto.so.10(OPENSSL_1.0.1)(64bit) is needed by (installed) ntp-4.2.6p5-1.el6.centos.x86_64
	libcrypto.so.10(OPENSSL_1.0.1)(64bit) is needed by (installed) openssh-server-5.3p1-94.el6.x86_64
	libcrypto.so.10(OPENSSL_1.0.1)(64bit) is needed by (installed) openssh-clients-5.3p1-94.el6.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by (installed) mysql-libs-5.1.71-1.el6.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by (installed) openssh-5.3p1-94.el6.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by (installed) ntpdate-4.2.6p5-1.el6.centos.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by (installed) ntp-4.2.6p5-1.el6.centos.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by (installed) openssh-server-5.3p1-94.el6.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by (installed) openssh-clients-5.3p1-94.el6.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by (installed) wget-1.12-1.11.el6_5.x86_64
	libssl.so.10()(64bit) is needed by (installed) libssh2-1.4.2-1.el6.x86_64
	libssl.so.10()(64bit) is needed by (installed) mysql-libs-5.1.71-1.el6.x86_64
	libssl.so.10()(64bit) is needed by (installed) python-libs-2.6.6-51.el6.x86_64
	libssl.so.10()(64bit) is needed by (installed) postfix-2:2.6.6-2.2.el6_1.x86_64
	libssl.so.10()(64bit) is needed by (installed) wget-1.12-1.11.el6_5.x86_64
	libssl.so.10()(64bit) is needed by (installed) git-1.7.1-3.el6_4.1.x86_64
	libssl.so.10(libssl.so.10)(64bit) is needed by (installed) mysql-libs-5.1.71-1.el6.x86_64
	libssl.so.10(libssl.so.10)(64bit) is needed by (installed) wget-1.12-1.11.el6_5.x86_64
[root@localhost rpmbuild]# more /etc/redhat-release 
CentOS release 6.5 (Final)
[root@localhost rpmbuild]#

**Comment by richbria** [comment]
You need to first install openssl-libs and then install openssl

**Comment by neverping** [comment]
Yeah, i did it! Now i'm seeing the curves, @richbria. Now I will try to figure it out what's the differences...

[root@localhost rpmbuild]# openssl ecparam -list_curves
  secp112r1 : SECG/WTLS curve over a 112 bit prime field
  secp112r2 : SECG curve over a 112 bit prime field
  secp128r1 : SECG curve over a 128 bit prime field
  secp128r2 : SECG curve over a 128 bit prime field
  secp160k1 : SECG curve over a 160 bit prime field
  secp160r1 : SECG curve over a 160 bit prime field
  secp160r2 : SECG/WTLS curve over a 160 bit prime field
  secp192k1 : SECG curve over a 192 bit prime field
  secp224k1 : SECG curve over a 224 bit prime field
  secp224r1 : NIST/SECG curve over a 224 bit prime field
  secp256k1 : SECG curve over a 256 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime192v1: NIST/X9.62/SECG curve over a 192 bit prime field
  prime192v2: X9.62 curve over a 192 bit prime field
  prime192v3: X9.62 curve over a 192 bit prime field
  prime239v1: X9.62 curve over a 239 bit prime field
  prime239v2: X9.62 curve over a 239 bit prime field
  prime239v3: X9.62 curve over a 239 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
  sect113r1 : SECG curve over a 113 bit binary field
  sect113r2 : SECG curve over a 113 bit binary field
  sect131r1 : SECG/WTLS curve over a 131 bit binary field
  sect131r2 : SECG curve over a 131 bit binary field
  sect163k1 : NIST/SECG/WTLS curve over a 163 bit binary field
  sect163r1 : SECG curve over a 163 bit binary field
  sect163r2 : NIST/SECG curve over a 163 bit binary field
  sect193r1 : SECG curve over a 193 bit binary field
  sect193r2 : SECG curve over a 193 bit binary field
  sect233k1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect233r1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect239k1 : SECG curve over a 239 bit binary field
  sect283k1 : NIST/SECG curve over a 283 bit binary field
  sect283r1 : NIST/SECG curve over a 283 bit binary field
  sect409k1 : NIST/SECG curve over a 409 bit binary field
  sect409r1 : NIST/SECG curve over a 409 bit binary field
  sect571k1 : NIST/SECG curve over a 571 bit binary field
  sect571r1 : NIST/SECG curve over a 571 bit binary field
  c2pnb163v1: X9.62 curve over a 163 bit binary field
  c2pnb163v2: X9.62 curve over a 163 bit binary field
  c2pnb163v3: X9.62 curve over a 163 bit binary field
  c2pnb176v1: X9.62 curve over a 176 bit binary field
  c2tnb191v1: X9.62 curve over a 191 bit binary field
  c2tnb191v2: X9.62 curve over a 191 bit binary field
  c2tnb191v3: X9.62 curve over a 191 bit binary field
  c2pnb208w1: X9.62 curve over a 208 bit binary field
  c2tnb239v1: X9.62 curve over a 239 bit binary field
  c2tnb239v2: X9.62 curve over a 239 bit binary field
  c2tnb239v3: X9.62 curve over a 239 bit binary field
  c2pnb272w1: X9.62 curve over a 272 bit binary field
  c2pnb304w1: X9.62 curve over a 304 bit binary field
  c2tnb359v1: X9.62 curve over a 359 bit binary field
  c2pnb368w1: X9.62 curve over a 368 bit binary field
  c2tnb431r1: X9.62 curve over a 431 bit binary field
  wap-wsg-idm-ecid-wtls1: WTLS curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls3: NIST/SECG/WTLS curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls4: SECG curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls5: X9.62 curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls6: SECG/WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls7: SECG/WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls8: WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls9: WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls10: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls11: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls12: WTLS curvs over a 224 bit prime field
  Oakley-EC2N-3: 
	IPSec/IKE/Oakley curve #3 over a 155 bit binary field.
	Not suitable for ECDSA.
	Questionable extension field!
  Oakley-EC2N-4: 
	IPSec/IKE/Oakley curve #4 over a 185 bit binary field.
	Not suitable for ECDSA.
	Questionable extension field!

**Comment by richbria** [comment]
I just tried to build that version of openssl on centos 6.6 and it did update openssl.  However, it breaks openssh.  

````
$ sudo service sshd restart
Stopping sshd:                                             [  OK  ]
Starting sshd: /usr/sbin/sshd: /usr/lib64/libcrypto.so.10: version `OPENSSL_1.0.1_EC' not found (required by /usr/sbin/sshd)
````

**Comment by neverping** [comment]
Hello @richbria:
Which build did you use that broke sshd? The actual build here or the previous one?

**Comment by neverping** [comment]
BTW, I'm still trying to figure it out a way to remove patches which implements FIPS and keep other patches. It requires some effort, because some other patches just fail because previous patches (those with FIPS) were not applied in sequence.

**Comment by neverping** [comment]
Ah, @richbria. This might have to do with issue #4 .

My openssl-1.0.1k works on centos 6.6. Here's my test with a vagrant box.

$ vagrant ssh
Last login: Thu Jan 22 09:36:20 2015 from 10.0.2.2
Welcome to your Packer-built virtual machine.
[vagrant@localhost ~]$ ls
openssl-1.0.1k-2.el6.x86_64.rpm        openssl-libs-1.0.1k-2.el6.x86_64.rpm  openssl-static-1.0.1k-2.el6.x86_64.rpm
openssl-devel-1.0.1k-2.el6.x86_64.rpm  openssl-perl-1.0.1k-2.el6.x86_64.rpm
[vagrant@localhost ~]$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
[vagrant@localhost ~]$ openssl ecparam -list_curves
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
[vagrant@localhost ~]$ sudo rpm -e openssl --nodeps
[vagrant@localhost ~]$ sudo rpm -ivh openssl-1.0.1k-2.el6.x86_64.rpm openssl-libs-1.0.1k-2.el6.x86_64.rpm 
Preparing...                ########################################### [100%]
   1:openssl-libs           ########################################### [ 50%]
   2:openssl                ########################################### [100%]
[vagrant@localhost ~]$ sudo service sshd restart
Stopping sshd:                                             [  OK  ]
Starting sshd:                                             [  OK  ]
[vagrant@localhost ~]$ cat /etc/redhat-release 
CentOS release 6.6 (Final)
[vagrant@localhost ~]$ openssl version
OpenSSL 1.0.1k-fips 8 Jan 2015
[vagrant@localhost ~]$ openssl ecparam -list_curves
  secp112r1 : SECG/WTLS curve over a 112 bit prime field
  secp112r2 : SECG curve over a 112 bit prime field
  secp128r1 : SECG curve over a 128 bit prime field
  secp128r2 : SECG curve over a 128 bit prime field
  secp160k1 : SECG curve over a 160 bit prime field
  secp160r1 : SECG curve over a 160 bit prime field
  secp160r2 : SECG/WTLS curve over a 160 bit prime field
  secp192k1 : SECG curve over a 192 bit prime field
  secp224k1 : SECG curve over a 224 bit prime field
  secp224r1 : NIST/SECG curve over a 224 bit prime field
  secp256k1 : SECG curve over a 256 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime192v1: NIST/X9.62/SECG curve over a 192 bit prime field
  prime192v2: X9.62 curve over a 192 bit prime field
  prime192v3: X9.62 curve over a 192 bit prime field
  prime239v1: X9.62 curve over a 239 bit prime field
  prime239v2: X9.62 curve over a 239 bit prime field
  prime239v3: X9.62 curve over a 239 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
  wap-wsg-idm-ecid-wtls6: SECG/WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls7: SECG/WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls8: WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls9: WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls12: WTLS curvs over a 224 bit prime field
[vagrant@localhost ~]$ 
--- testing clients with SSL
[vagrant@localhost ~]$ curl -sI https://www.openssl.org
HTTP/1.1 200 OK
Date: Thu, 22 Jan 2015 17:52:48 GMT
Server: Apache/2.2.22 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Length: 14548
Content-Type: text/html; charset=UTF-8

[vagrant@localhost ~]$ wget -O /dev/null https://www.openssl.org
--2015-01-22 09:52:49--  https://www.openssl.org/
Resolving www.openssl.org... 185.9.166.106
Connecting to www.openssl.org|185.9.166.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14548 (14K) [text/html]
Saving to: “/dev/null”

100%[====================================================================================================================>] 14,548      49.9K/s   in 0.3s    

2015-01-22 09:52:55 (49.9 KB/s) - “/dev/null” saved [14548/14548]

[vagrant@localhost ~]$

**Comment by neverping** [comment]
Hello @tittof 

Well, I did some tries, but unfortunately I couldn't make it work nicely. 

Essentially, I'm not good with C/C++ so I can't just remove / add code without being pretty sure what's happening, because I would like to make a stable RPM which could work in every single way and the maximum compatibility with Fedora building, with extra features we might want it.

I will try again tomorrow to remove fips and I will try to fix patches, which could break things. But I think it will be harder to maintain it for the next openssl releases. =(

**Comment by neverping** [comment]
Well, I couldn't make it. Always getting small errors and so on. =(

What I almost did was remove every patch and just apply the "secure_getenv" patch and compile OpenSSL. Unfortunately I don't have any more spare time to try more. If I got time, i will try.

**Comment by tittof** [comment]
if you get  version `OPENSSL_1.0.1_EC' not found (required by /usr/sbin/sshd)

then it is a clear sign of not having used my https://github.com/tittof/centos6-openssl

Because one would have to make it so that the version patch gets that in.

**Comment by ptudor** [comment]
A diff in a comment is nice, but push changes and I'll merge them, I just won't commit anything myself. See: ITAR. Also, my own OpenSSL RPMs are fine without FIPS, but I'm not a defense contractor so it's easy to abandon.

```
% cat /etc/redhat-release 
CentOS release 6.6 (Final)
% openssl ecparam -list_curves
  secp112r1 : SECG/WTLS curve over a 112 bit prime field
  secp112r2 : SECG curve over a 112 bit prime field
  secp128r1 : SECG curve over a 128 bit prime field
  secp128r2 : SECG curve over a 128 bit prime field
  secp160k1 : SECG curve over a 160 bit prime field
  secp160r1 : SECG curve over a 160 bit prime field
  secp160r2 : SECG/WTLS curve over a 160 bit prime field
  secp192k1 : SECG curve over a 192 bit prime field
  secp224k1 : SECG curve over a 224 bit prime field
  secp224r1 : NIST/SECG curve over a 224 bit prime field
  secp256k1 : SECG curve over a 256 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime192v1: NIST/X9.62/SECG curve over a 192 bit prime field
  prime192v2: X9.62 curve over a 192 bit prime field
  prime192v3: X9.62 curve over a 192 bit prime field
  prime239v1: X9.62 curve over a 239 bit prime field
  prime239v2: X9.62 curve over a 239 bit prime field
  prime239v3: X9.62 curve over a 239 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
  sect113r1 : SECG curve over a 113 bit binary field
  sect113r2 : SECG curve over a 113 bit binary field
  sect131r1 : SECG/WTLS curve over a 131 bit binary field
  sect131r2 : SECG curve over a 131 bit binary field
  sect163k1 : NIST/SECG/WTLS curve over a 163 bit binary field
  sect163r1 : SECG curve over a 163 bit binary field
  sect163r2 : NIST/SECG curve over a 163 bit binary field
  sect193r1 : SECG curve over a 193 bit binary field
  sect193r2 : SECG curve over a 193 bit binary field
  sect233k1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect233r1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect239k1 : SECG curve over a 239 bit binary field
  sect283k1 : NIST/SECG curve over a 283 bit binary field
  sect283r1 : NIST/SECG curve over a 283 bit binary field
  sect409k1 : NIST/SECG curve over a 409 bit binary field
  sect409r1 : NIST/SECG curve over a 409 bit binary field
  sect571k1 : NIST/SECG curve over a 571 bit binary field
  sect571r1 : NIST/SECG curve over a 571 bit binary field
  c2pnb163v1: X9.62 curve over a 163 bit binary field
  c2pnb163v2: X9.62 curve over a 163 bit binary field
  c2pnb163v3: X9.62 curve over a 163 bit binary field
  c2pnb176v1: X9.62 curve over a 176 bit binary field
  c2tnb191v1: X9.62 curve over a 191 bit binary field
  c2tnb191v2: X9.62 curve over a 191 bit binary field
  c2tnb191v3: X9.62 curve over a 191 bit binary field
  c2pnb208w1: X9.62 curve over a 208 bit binary field
  c2tnb239v1: X9.62 curve over a 239 bit binary field
  c2tnb239v2: X9.62 curve over a 239 bit binary field
  c2tnb239v3: X9.62 curve over a 239 bit binary field
  c2pnb272w1: X9.62 curve over a 272 bit binary field
  c2pnb304w1: X9.62 curve over a 304 bit binary field
  c2tnb359v1: X9.62 curve over a 359 bit binary field
  c2pnb368w1: X9.62 curve over a 368 bit binary field
  c2tnb431r1: X9.62 curve over a 431 bit binary field
  wap-wsg-idm-ecid-wtls1: WTLS curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls3: NIST/SECG/WTLS curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls4: SECG curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls5: X9.62 curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls6: SECG/WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls7: SECG/WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls8: WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls9: WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls10: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls11: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls12: WTLS curvs over a 224 bit prime field
  Oakley-EC2N-3: 
	IPSec/IKE/Oakley curve #3 over a 155 bit binary field.
	Not suitable for ECDSA.
	Questionable extension field!
  Oakley-EC2N-4: 
	IPSec/IKE/Oakley curve #4 over a 185 bit binary field.
	Not suitable for ECDSA.
	Questionable extension field!
%
```

**Comment by tittof** [comment]
@ptudor: you simply IGNORING THE FACT, that other packages are built against the OPENSSL_1.0.1_EC dependency. And you have been informed of that MALFUNCTIONING Package in that other ticket. Now you close this ticket with unrelated foo talking about defense contractor bull**. Packages in Fedora/RHEL EXPECT having the Version export OPENSSL_1.0.1_EC in the openssl package.

**Comment by ptudor** [comment]
I closed the ticket because no one has sent anything to merge. Tickets are nice, but fixes are actually useful. The history of the repo reveals I have authored nothing but a spec file nearly two years ago and quickly merged every contribution. I'll check to see if I've missed your contribution that fixes this issue.
